openapi: 3.0.0
info:
  title: Multiply API
  description: A simple API to multiply numbers.
  version: 1.0.0
paths:
  /multiply/{id}:
    get:
      summary: Multiply a number by 10
      description: Multiplies the provided number by 10.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The number to be multiplied by 10
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: integer
        '400':
          description: Invalid input